### ISSUE TITLE
Youtube video's werken niet :(

### ISSUE THREAD

**Issue by acidtv** [jieter/planning-poker#43]
![image](https://github.com/jieter/planning-poker/assets/409442/7530e6cb-15ec-4586-9716-ecae6232b309)

**Comment by acidtv** [comment]
@jieter

**Comment by jieter** [comment]
Heb je een adblocker?

**Comment by jieter** [comment]
In mijn kale firefox werkt het prima

<img width="1108" alt="Screenshot 2023-12-16 at 09 25 25" src="https://github.com/jieter/planning-poker/assets/1470389/b14aae29-012e-44ca-802d-b4fa6d99e904">

**Comment by acidtv** [comment]
Ik heb een adblocker, maar als ik die uitzet werkt het nog steeds niet

**Comment by acidtv** [comment]
Ah, op poker.datala werkt het wel. Misschien iets met https ofzo.

**Comment by jieter** [comment]
Ja, daar las ik inderdaad ook wat over, bij mij werkt het wel op localhost gek genoeg
